### ISSUE TITLE
May I be a contributor of your project?

### ISSUE THREAD

**Issue by LainHE** [ssklykov/GObj_Movement#1]
I am an IT student who studying Open Source Software.
I have to contribute and communicate with people on the GitHub.
Actually, I am a newbie about coding, but I could to contribute and help your in different ways.
For examples, writing documentation, design and error correction.
I am also doing the project that blurred images restoration with MATLAB.
The reason why I want join is, I want to learn and understand your method.
BTW, I am a Chinese student, so I could create a Chinese version for you if it is needed.

Sorry for this
I could not find your public email, so I have to put a issue for asking about that at the end.
Here is my public email by the way: TH591@live.mdx.ac.uk

**Comment by sklykov** [comment]
Wow! 
I didn't expect that someone will be curious about this side project. 
Anyway, I will contact you with provided email. 

Thanks!

**Comment by LainHE** [comment]
I can't help you a lot, because I am really a freshman of coding.
But I could write a Chinese version of the project for you. That might help you to grab more people's interest.
I also could try to help you with error correction. But I also have heavy work to do with other module of study. It might take slower period, becuase I have to learn how your project works. I have to order that which should go first.

**Comment by sklykov** [comment]
I wrote your an email. I close this issue since I contact you
